import React from 'react';
import { 
  MessageSquare, 
  Instagram, 
  Facebook, 
  Send, 
  Music2,
  Smartphone
} from 'lucide-react';

export interface ServiceItem {
  name: string;
  price: number;
  apiName: string;
  icon?: React.ReactNode;
}

export const SERVICE_CATALOG: Record<string, ServiceItem[]> = {
  "SOCIAL MEDIA APPS": [
    { name: "WhatsApp", price: 800, apiName: "whatsapp", icon: <MessageSquare size={24} /> },
    { name: "Instagram", price: 1000, apiName: "instagram", icon: <Instagram size={24} /> },
    { name: "Facebook", price: 800, apiName: "facebook", icon: <Facebook size={24} /> },
    { name: "Telegram", price: 600, apiName: "telegram", icon: <Send size={24} /> },
    { name: "TikTok", price: 1000, apiName: "tiktok", icon: <Music2 size={24} /> },
    { name: "Twitter / X", price: 1200, apiName: "twitter" },
    { name: "Snapchat", price: 1000, apiName: "snapchat" },
    { name: "LinkedIn", price: 1200, apiName: "linkedin" },
    { name: "Pinterest", price: 800, apiName: "pinterest" },
    { name: "YouTube", price: 1000, apiName: "youtube" },
    { name: "Threads", price: 1000, apiName: "threads" },
    { name: "BeReal", price: 800, apiName: "bereal" },
    { name: "Discord", price: 800, apiName: "discord" },
    { name: "Tumblr", price: 600, apiName: "tumblr" },
    { name: "Reddit", price: 800, apiName: "reddit" },
    { name: "Clubhouse", price: 800, apiName: "clubhouse" },
    { name: "Viber", price: 600, apiName: "viber" },
    { name: "Signal", price: 800, apiName: "signal" },
    { name: "Line", price: 600, apiName: "line" },
    { name: "WeChat", price: 1200, apiName: "wechat" },
    { name: "Skype", price: 800, apiName: "skype" },
    { name: "Kik", price: 600, apiName: "kik" },
    { name: "MeWe", price: 600, apiName: "mewe" },
    { name: "Mastodon", price: 600, apiName: "mastodon" },
  ],
  "MOBILE BANKING & FINTECH": [
    { name: "OPay", price: 1500, apiName: "opay" },
    { name: "Kuda Bank", price: 1500, apiName: "kuda" },
    { name: "PalmPay", price: 1500, apiName: "palmpay" },
    { name: "Moniepoint", price: 1500, apiName: "moniepoint" },
    { name: "Carbon", price: 1500, apiName: "carbon" },
    { name: "FairMoney", price: 1500, apiName: "fairmoney" },
    { name: "Branch", price: 1500, apiName: "branch" },
    { name: "Piggyvest", price: 1500, apiName: "piggyvest" },
    { name: "Cowrywise", price: 1500, apiName: "cowrywise" },
    { name: "Chipper Cash", price: 1500, apiName: "chippercash" },
    { name: "Flutterwave", price: 1500, apiName: "flutterwave" },
    { name: "Paystack", price: 1500, apiName: "paystack" },
    { name: "GTBank Mobile", price: 2000, apiName: "gtbank" },
    { name: "Access Bank App", price: 2000, apiName: "accessbank" },
    { name: "Zenith Bank App", price: 2000, apiName: "zenithbank" },
    { name: "First Bank App", price: 2000, apiName: "firstbank" },
    { name: "UBA Mobile", price: 2000, apiName: "uba" },
    { name: "Stanbic Mobile", price: 2000, apiName: "stanbic" },
    { name: "Sterling Bank", price: 2000, apiName: "sterling" },
    { name: "Fidelity Mobile", price: 2000, apiName: "fidelity" },
    { name: "Ecobank App", price: 2000, apiName: "ecobank" },
    { name: "Union Bank App", price: 2000, apiName: "unionbank" },
    { name: "Polaris Bank", price: 2000, apiName: "polaris" },
    { name: "Wema Bank ALAT", price: 1500, apiName: "wema" },
    { name: "Revolut", price: 2000, apiName: "revolut" },
    { name: "Wise", price: 2000, apiName: "wise" },
    { name: "Cash App", price: 2000, apiName: "cashapp" },
    { name: "PayPal", price: 2500, apiName: "paypal" },
    { name: "Venmo", price: 2000, apiName: "venmo" },
    { name: "Stripe", price: 2500, apiName: "stripe" },
    { name: "Skrill", price: 2000, apiName: "skrill" },
    { name: "Neteller", price: 2000, apiName: "neteller" },
    { name: "Payoneer", price: 2500, apiName: "payoneer" },
    { name: "Binance", price: 2000, apiName: "binance" },
    { name: "Coinbase", price: 2500, apiName: "coinbase" },
    { name: "Bybit", price: 2000, apiName: "bybit" },
    { name: "KuCoin", price: 2000, apiName: "kucoin" },
    { name: "OKX", price: 2000, apiName: "okx" },
    { name: "Luno", price: 1500, apiName: "luno" },
    { name: "Paxful", price: 1500, apiName: "paxful" },
  ],
  "EMAIL & GOOGLE SERVICES": [
    { name: "Gmail", price: 1500, apiName: "gmail" },
    { name: "Google Account", price: 1500, apiName: "google" },
    { name: "Yahoo Mail", price: 1200, apiName: "yahoo" },
    { name: "Outlook", price: 1200, apiName: "outlook" },
    { name: "ProtonMail", price: 1200, apiName: "protonmail" },
    { name: "Zoho Mail", price: 1000, apiName: "zoho" },
    { name: "iCloud", price: 2000, apiName: "icloud" },
    { name: "AOL Mail", price: 1000, apiName: "aol" },
    { name: "Yandex Mail", price: 800, apiName: "yandex" },
    { name: "Temp Mail Pro", price: 800, apiName: "tempmail" },
  ],
  "RIDE & DELIVERY APPS": [
    { name: "Uber", price: 1500, apiName: "uber" },
    { name: "Bolt", price: 1500, apiName: "bolt" },
    { name: "inDrive", price: 1200, apiName: "indrive" },
    { name: "Gokada", price: 1200, apiName: "gokada" },
    { name: "Max.ng", price: 1200, apiName: "maxng" },
    { name: "Glovo", price: 1200, apiName: "glovo" },
    { name: "Jumia Food", price: 1200, apiName: "jumiafood" },
    { name: "Chowdeck", price: 1200, apiName: "chowdeck" },
    { name: "DoorDash", price: 1500, apiName: "doordash" },
    { name: "Uber Eats", price: 1500, apiName: "ubereats" },
    { name: "Lyft", price: 1500, apiName: "lyft" },
  ],
  "SHOPPING": [
    { name: "Amazon", price: 1500, apiName: "amazon" },
    { name: "eBay", price: 1200, apiName: "ebay" },
    { name: "Alibaba", price: 1000, apiName: "alibaba" },
    { name: "AliExpress", price: 1000, apiName: "aliexpress" },
    { name: "Jumia", price: 800, apiName: "jumia" },
    { name: "Konga", price: 800, apiName: "konga" },
  ],
  "DATING": [
    { name: "Tinder", price: 2000, apiName: "tinder" },
    { name: "Bumble", price: 2000, apiName: "bumble" },
    { name: "Badoo", price: 1500, apiName: "badoo" },
    { name: "OkCupid", price: 1500, apiName: "okcupid" },
  ],
  "STREAMING": [
    { name: "Netflix", price: 2500, apiName: "netflix" },
    { name: "Spotify", price: 1500, apiName: "spotify" },
    { name: "Apple Music", price: 1500, apiName: "applemusic" },
    { name: "YouTube Premium", price: 2000, apiName: "youtube" },
    { name: "Disney+", price: 2000, apiName: "disneyplus" },
  ],
  "GAMING": [
    { name: "Steam", price: 1500, apiName: "steam" },
    { name: "PlayStation", price: 2000, apiName: "playstation" },
    { name: "Xbox", price: 2000, apiName: "xbox" },
    { name: "Epic Games", price: 1500, apiName: "epicgames" },
    { name: "Roblox", price: 1200, apiName: "roblox" },
    { name: "PUBG", price: 1200, apiName: "pubg" },
  ],
  "CRYPTO": [
    { name: "Binance", price: 2000, apiName: "binance" },
    { name: "Coinbase", price: 2500, apiName: "coinbase" },
    { name: "Trust Wallet", price: 1500, apiName: "trustwallet" },
    { name: "MetaMask", price: 1500, apiName: "metamask" },
    { name: "KuCoin", price: 2000, apiName: "kucoin" },
  ],
  "NIGERIAN APPS": [
    { name: "OPay", price: 1500, apiName: "opay" },
    { name: "PalmPay", price: 1500, apiName: "palmpay" },
    { name: "Kuda", price: 1500, apiName: "kuda" },
    { name: "Cowrywise", price: 1500, apiName: "cowrywise" },
    { name: "Piggyvest", price: 1500, apiName: "piggyvest" },
  ]
};
